modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Darkona/feathers-of-fatigue/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "feathers.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cold_sweat"
mandatory = false
versionRange = "${cold_sweat_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "thirst"
mandatory = false
versionRange = "${thirst_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "overflowingbars"
mandatory = false
versionRange = "${overflowing_bars_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
mandatory = false
versionRange = "${curios_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jade"
mandatory = false
versionRange = "${jade_range}"
ordering = "NONE"
side = "BOTH"
