modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Darkona/feathers-of-fatigue/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "feathers.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cold_sweat"
type = "optional"
versionRange = "${cold_sweat_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "thirst"
type = "optional"
versionRange = "${thirst_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "droplets_of_thirst"
type = "optional"
versionRange = "${droplets_of_thirst_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "toughasnails"
type = "optional"
versionRange = "${tough_as_nails_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sereneseasons"
type = "optional"
versionRange = "${serene_seasons_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "legendarysurvivaloverhaul"
type = "optional"
versionRange = "${lso_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "overflowingbars"
type = "optional"
versionRange = "${overflowing_bars_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "${curios_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jade"
type = "optional"
versionRange = "${jade_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "feathers_of_fatigue.mixins.json"
